### PR TITLE
#2 Implement Firebase Google Login

### LINKED ISSUE #2: Firebase Google Login In

### PR DESCRIPTION
**Pull request by its-me-mahmud**
Implemented authentication with Firebase Google Sign In

### CODE REVIEW

**Review by momshaddinury — CHANGES_REQUESTED** [review]
Please remove 

- .flutter-plugins
- .flutter-plugins-dependencies
- .packages
- pubspec.lock

**Comment by its-me-mahmud** [comment]
Can you elaborate what's the problem these files make you mention above?
I added **google_sign_in** package so those files are updated with this after `flutter pub get`.

**Comment by momshaddinury** [comment]
Generated files like the ones mentioned above shouldn't be committed. See here https://dart.dev/guides/libraries/private-files

**Comment by its-me-mahmud** [comment]
Oh I forgot thanks for reminding me. And I've reimplemented the code. You can check

**Review by momshaddinury — APPROVED** [review]

**Comment by momshaddinury** [comment]
@its-me-mahmud can you test google sign in and confirm if it's working?

**Comment by its-me-mahmud** [comment]
@dinurymomshad not working please check

**Comment by momshaddinury** [comment]
> @dinurymomshad not working please check

Hi this is working. Switch to main, do a clean clone and run the app. It is working fine.

**Comment by its-me-mahmud** [comment]
On mobile:
```dart
W/ActivityThread( 5316): handleWindowVisibility: no activity for token android.os.BinderProxy@fe1f5fb
I/flutter ( 5316): ┌───────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
I/flutter ( 5316): │ #0   Log.error (package:listify/core/logger.dart:31:59)
package:listify/core/logger.dart:31
I/flutter ( 5316): │ #1   AuthenticationController.signInWithGoogle (package:listify/feature/authentication/controllers/authentication_controller.dart:58:11)
package:listify/…/controllers/authentication_controller.dart:58
I/flutter ( 5316): ├┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄
I/flutter ( 5316): │ ⛔ PlatformException(sign_in_failed, com.google.android.gms.common.api.ApiException: 10: , null, null)
I/flutter ( 5316): └───────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
I/flutter ( 5316): ┌───────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
I/flutter ( 5316): │ #0   Log.error (package:listify/core/logger.dart:31:59)
package:listify/core/logger.dart:31
I/flutter ( 5316): │ #1   AuthenticationController.signInWithGoogle (package:listify/feature/authentication/controllers/authentication_controller.dart:59:11)
package:listify/…/controllers/authentication_controller.dart:59
I/flutter ( 5316): ├┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄
I/flutter ( 5316): │ ⛔ #0      StandardMethodCodec.decodeEnvelope (package:flutter/src/services/message_codecs.dart:607:7)
package:flutter/…/services/message_codecs.dart:607
I/flutter ( 5316): │ ⛔ #1      MethodChannel._invokeMethod (package:flutter/src/services/platform_channel.dart:167:18)
package:flutter/…/services/platform_channel.dart:167
I/flutter ( 5316): │ ⛔ <asynchronous suspension>
I/flutter ( 5316): │ ⛔ #2      MethodChannel.invokeMapMethod (package:flutter/src/services/platform_channel.dart:367:43)
package:flutter/…/services/platform_channel.dart:367
I/flutter ( 5316): │ ⛔ <asynchronous suspension>
I/flutter ( 5316): │ ⛔ #3      GoogleSignIn._callMethod (package:google_sign_in/google_sign_in.dart:247:30)
package:google_sign_in/google_sign_in.dart:247
I/flutter ( 5316): │ ⛔ <asynchronous suspension>
I/flutter ( 5316): │ ⛔ #4      GoogleSignIn.signIn.isCanceled (package:google_sign_in/google_sign_in.dart:377:5)
package:google_sign_in/google_sign_in.dart:377
I/flutter ( 5316): │ ⛔ <asynchronous suspension>
I/flutter ( 5316): │ ⛔ 
I/flutter ( 5316): └───────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
```

But on the web, the app successfully logged in but errored with a red screen on HomePage.
BTW I migrated to Flutter 3. Is it not working because of that. I'm not sure

**Comment by its-me-mahmud** [comment]
@dinurymomshad kindly migrate to Flutter 3

**Pull request merged**
